export const EVENT_ICONS = [
  { emoji: '🍽️', label: 'Middag' },
  { emoji: '🎂', label: 'Bursdag' },
  { emoji: '🎉', label: 'Fest' },
  { emoji: '⚽', label: 'Sport' },
  { emoji: '✈️', label: 'Reise' },
  { emoji: '🏫', label: 'Skole' },
  { emoji: '🍕', label: 'Restaurant' },
  { emoji: '🏖️', label: 'Ferie' },
  { emoji: '🎬', label: 'Kino' },
  { emoji: '🎵', label: 'Konsert' },
  { emoji: '💪', label: 'Trening' },
  { emoji: '🎄', label: 'Høytid' },
  { emoji: '👶', label: 'Barnedag' },
  { emoji: '🏡', label: 'Hjemme' },
  { emoji: '🎮', label: 'Spill' },
  { emoji: '☕', label: 'Kaffe' },
  { emoji: '🏃', label: 'Løping' },
  { emoji: '🚴', label: 'Sykling' },
  { emoji: '🏔️', label: 'Fjelltur' },
  { emoji: '🎣', label: 'Fiske' },
];
