export const EVENT_ICONS = [
  { icon: 'middag', label: 'Middag' },
  { icon: 'bursdag', label: 'Bursdag' },
  { icon: 'fest', label: 'Fest' },
  { icon: 'sport', label: 'Sport' },
  { icon: 'restaurant', label: 'Restaurant' },
  { icon: 'kino', label: 'Kino' },
  { icon: 'konsert', label: 'Konsert' },
  { icon: 'trening', label: 'Trening' },
  { icon: 'hoytid', label: 'Høytid' },
  { icon: 'barnedag', label: 'Barnedag' },
  { icon: 'hjemme', label: 'Hjemme' },
  { icon: 'spill', label: 'Spill' },
  { icon: 'kaffe', label: 'Kaffe' },
  { icon: 'loping', label: 'Løping' },
  { icon: 'sykling', label: 'Sykling' },
  { icon: 'fjelltur', label: 'Fjelltur' },
  { icon: 'fiske', label: 'Fiske' },
  { icon: 'cheerleading', label: 'Cheerleading' },
  { icon: 'racketsport', label: 'Racketsport' },
  { icon: 'tur', label: 'Tur' },
];
