export const lightColors = {
  background: '#f5f5f5',
  surface: '#fff',
  surfaceVariant: '#f0f0f0',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#eee',
  accent: '#4CAF50',
  accentLight: '#E8F5E9',
  danger: '#ff4444',
  chatBubbleOwn: '#4CAF50',
  chatBubbleOther: '#e5e5ea',
  chatTextOwn: '#fff',
  chatTextOther: '#000',
  inputBackground: '#f5f5f5',
  statusBar: 'dark',
} as const;

export const darkColors = {
  background: '#121212',
  surface: '#1e1e1e',
  surfaceVariant: '#2c2c2e',
  text: '#e0e0e0',
  textSecondary: '#a0a0a0',
  textDisabled: '#666',
  border: '#333',
  accent: '#4CAF50',
  accentLight: '#1b3a1e',
  danger: '#ff6b6b',
  chatBubbleOwn: '#4CAF50',
  chatBubbleOther: '#2c2c2e',
  chatTextOwn: '#fff',
  chatTextOther: '#e0e0e0',
  inputBackground: '#2c2c2e',
  statusBar: 'light',
} as const;

export const orangeColors = {
  background: '#faf6f3',
  surface: '#fff',
  surfaceVariant: '#f5ede8',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#f0e0d4',
  accent: '#E87C3E',
  accentLight: '#FBE9D7',
  danger: '#ff4444',
  chatBubbleOwn: '#E87C3E',
  chatBubbleOther: '#f0e0d4',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#faf6f3',
  statusBar: 'dark',
} as const;

export const deepBlueColors = {
  background: '#f2f5f8',
  surface: '#fff',
  surfaceVariant: '#e8eef4',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#d4e0ed',
  accent: '#1A3A5C',
  accentLight: '#D6E4F0',
  danger: '#ff4444',
  chatBubbleOwn: '#1A3A5C',
  chatBubbleOther: '#d4e0ed',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#f2f5f8',
  statusBar: 'dark',
} as const;

export const silverColors = {
  background: '#f5f5f5',
  surface: '#fff',
  surfaceVariant: '#ebebeb',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#ddd',
  accent: '#8E8E93',
  accentLight: '#E8E8EA',
  danger: '#ff4444',
  chatBubbleOwn: '#8E8E93',
  chatBubbleOther: '#e5e5ea',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#f5f5f5',
  statusBar: 'dark',
} as const;

export const purpleColors = {
  background: '#f7f2fa',
  surface: '#fff',
  surfaceVariant: '#f0e8f5',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#e4d4f0',
  accent: '#9C27B0',
  accentLight: '#F3E5F5',
  danger: '#ff4444',
  chatBubbleOwn: '#9C27B0',
  chatBubbleOther: '#e4d4f0',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#f7f2fa',
  statusBar: 'dark',
} as const;

export const pinkColors = {
  background: '#fdf5f7',
  surface: '#fff',
  surfaceVariant: '#f9edf1',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#f3dde4',
  accent: '#F48FB1',
  accentLight: '#FDE4EC',
  danger: '#ff4444',
  chatBubbleOwn: '#F48FB1',
  chatBubbleOther: '#f3dde4',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#fdf5f7',
  statusBar: 'dark',
} as const;

export const tealColors = {
  background: '#f2f8f9',
  surface: '#fff',
  surfaceVariant: '#e5f0f2',
  text: '#333',
  textSecondary: '#666',
  textDisabled: '#999',
  border: '#d0e4e8',
  accent: '#0097A7',
  accentLight: '#E0F2F1',
  danger: '#ff4444',
  chatBubbleOwn: '#0097A7',
  chatBubbleOther: '#d0e4e8',
  chatTextOwn: '#fff',
  chatTextOther: '#333',
  inputBackground: '#f2f8f9',
  statusBar: 'dark',
} as const;

export const darkTealColors = {
  background: '#f0f7f7',
  surface: '#fff',
  surfaceVariant: '#e2efef',
  text: '#1a1a1a',
  textSecondary: '#555',
  textDisabled: '#999',
  border: '#c8e0e0',
  accent: '#096061',
  accentLight: '#D6EDED',
  danger: '#ff4444',
  chatBubbleOwn: '#096061',
  chatBubbleOther: '#c8e0e0',
  chatTextOwn: '#fff',
  chatTextOther: '#1a1a1a',
  inputBackground: '#f0f7f7',
  statusBar: 'dark',
} as const;

export type Colors = typeof lightColors;
